spring:
  profiles:
    active: local

---
spring:
  config:
    activate:
      on-profile: local

  messages:
    basename: errors

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: false
    open-in-view: false

  datasource:
    url: jdbc:h2:tcp://localhost/~/board
    username: sa
    password:
    driver-class-name: org.h2.Driver

server:
  servlet:
    session:
      tracking-modes: cookie

  port: 5000


logging:
  level:
    org.hibernate.SQL: debug

---
spring:
  config:
    activate:
      on-profile: prod

  messages:
    basename: errors

  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: false
        use_sql_comments: false
    open-in-view: false

server:
  servlet:
    session:
      tracking-modes: cookie

  port: 5000

logging:
  level:
    org.hibernate.SQL: debug