spring:
  messages:
    basename: errors

  jpa:
    open-in-view: false

server:
  servlet:
    session:
      tracking-modes: cookie
  tomcat:
    mbeanregistry:
      enabled: true

view:
  board:
    article-page-size: 10
    comment-page-size: 20

management:
  endpoints:
    web:
      exposure:
        include: "*"
---
spring:
  config:
    activate:
      on-profile: local
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: false
  datasource:
    url: jdbc:h2:tcp://localhost/~/newboard
    username: sa
    password:
    driver-class-name: org.h2.Driver

logging:
  level:
    org.hibernate.SQL: debug

